apiVersion: v1
kind: Secret
metadata:
  name: azvaultwatch
type: Opaque
stringData:
  APP_INSIGHTS_CONN_STRING: InstrumentationKey=3bea50e6-7229-4d51-b18a-21e3c8cc4d84;IngestionEndpoint=https://southeastasia-1.in.applicationinsights.azure.com/;LiveEndpoint=https://southeastasia.livediagnostics.monitor.azure.com/;ApplicationId=907c38c2-78c0-421f-84db-b18f9e13d497
  SMTP_CONFIG: |
   {
    "host": "smtp.azurecomm.net",
    "port": 587,
    "username":"commsvc-apac-dev.b6df10d2-13d4-4026-a3f0-d78bb4bc3d0c.f9f26aa0-c90e-4431-add4-7749d97ba420",
    "password": "spn client secret is used by azure comm service email SMTP server as SMTP password",
    "subject": "Azure Key Vault Expiring Artifacts",
    "senderAddress": "DoNotReply@674edb48-246c-4119-ac71-7eabf6c96aa5.azurecomm.net",
    "to": ["weixzha@microsoft.com"],
    "cc": []
   }